<a href="https://colab.research.google.com/github/gauravcr7rm/Emotion-detection-using-audio-signals/blob/main/speech_data_processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!cd /content/sample_data

In [ ]:
import pickle

In [ ]:
import pandas as pd
df = pd.read_csv('/content/drive/My Drive/spectroimage_folder/test_sent_emo.csv')

In [ ]:
df.apply(pd.Series.value_counts)

Sr No.  ...  EndTime
0                                                      NaN  ...      NaN
1                                                      1.0  ...      NaN
2                                                      1.0  ...      NaN
3                                                      1.0  ...      NaN
4                                                      NaN  ...      NaN
...                                                    ...  ...      ...
surprise                                               NaN  ...      NaN
then a little more custard, and then bananas, a...     NaN  ...      NaN
‘Cause let’s face it, we’re at Monica’s.               NaN  ...      NaN
‘Kay look, if I have to go to the doctor for an...     NaN  ...      NaN
“...I can begin to trust you again.                    NaN  ...      NaN

[9809 rows x 11 columns]

In [ ]:
t = df['Emotion']
import numpy as np

In [ ]:
a,b = np.unique(t,return_counts='True')

In [ ]:
a,b

(array(['anger', 'disgust', 'fear', 'joy', 'neutral', 'sadness',
        'surprise'], dtype=object),
 array([ 345,   68,   50,  402, 1256,  208,  281]))

In [ ]:
df.describe()

Sr No.  Dialogue_ID  Utterance_ID       Season      Episode
count  2610.000000  2610.000000   2610.000000  2610.000000  2610.000000
mean   1382.552107   140.368582      5.918774     4.804981    12.497318
std     793.009903    79.549222      4.991015     2.247074     7.224232
min       1.000000     0.000000      0.000000     1.000000     1.000000
25%     700.250000    72.000000      2.000000     3.000000     6.000000
50%    1371.500000   139.000000      5.000000     5.000000    12.000000
75%    2068.500000   206.750000      9.000000     6.000000    20.000000
max    2764.000000   279.000000     32.000000     9.000000    25.000000

In [ ]:
filename = 'X_train_audio_mfcc'
infile = open('/content/drive/My Drive/X_train_audio_mfcc.pickle', 'rb')

In [ ]:
x_train = pickle.load(infile)

In [ ]:
print(x_train)

[[-2.30572037e+02  8.75856400e+01 -1.23138170e+01 ... -1.06383669e+00
  -3.89006472e+00 -1.75972927e+00]
 [-2.29853622e+02  1.08583725e+02 -4.83091316e+01 ...  2.56302738e+00
  -3.23568285e-01  1.78915903e-01]
 [-2.40808304e+02  8.28141632e+01 -1.66603107e+01 ...  7.14137018e-01
  -1.51153654e-01  3.03361535e+00]
 ...
 [-2.94260071e+02  1.12519043e+02 -4.08921928e+01 ...  8.40909332e-02
  -7.91240275e-01  1.98593581e+00]
 [-3.46273315e+02  1.08435432e+02 -3.69318390e+01 ... -8.31725597e-01
  -9.09745991e-01  1.41837215e+00]
 [-3.38791840e+02  1.12948410e+02 -1.06068754e+01 ... -1.54717612e+00
  -5.77455521e+00 -2.56772447e+00]]


In [ ]:
x_train.shape

(9933, 40)

In [ ]:
x_train_dict.dtype

dtype('float32')

In [ ]:
import pandas as pd
feat_cols = ['feature'+str(i) for i in range(x_train.shape[1])]
x_train_pd = pd.DataFrame(x_train,columns=feat_cols)

In [ ]:
x_train_pd.head()

feature0    feature1   feature2  ...  feature37  feature38  feature39
0 -230.572037   87.585640 -12.313817  ...  -1.063837  -3.890065  -1.759729
1 -229.853622  108.583725 -48.309132  ...   2.563027  -0.323568   0.178916
2 -240.808304   82.814163 -16.660311  ...   0.714137  -0.151154   3.033615
3 -266.381714   59.375847  -8.897157  ...  -0.132388  -1.208127   0.947963
4 -267.787292   64.038872 -14.584082  ...  -0.557864  -2.350834   0.591544

[5 rows x 40 columns]

In [ ]:
x_train_pd.describe()

feature0     feature1  ...    feature38    feature39
count  9933.000000  9933.000000  ...  9933.000000  9933.000000
mean   -310.995636    98.332535  ...    -2.095678     0.485678
std      67.051331    19.793501  ...     2.288146     2.209995
min    -656.663452   -28.103149  ...   -13.625463    -9.638582
25%    -352.173462    86.089294  ...    -3.503619    -0.871224
50%    -309.853302    99.614166  ...    -2.204217     0.409643
75%    -266.818268   111.828705  ...    -0.858127     1.701399
max     -78.340118   171.529709  ...    25.058451    22.633249

[8 rows x 40 columns]

In [ ]:
x_train_pd.apply(pd.Series.value_counts)

feature0  feature1  feature2  ...  feature37  feature38  feature39
-656.663452       1.0       NaN       NaN  ...        NaN        NaN        NaN
-604.945129       1.0       NaN       NaN  ...        NaN        NaN        NaN
-587.187866       1.0       NaN       NaN  ...        NaN        NaN        NaN
-585.821167       1.0       NaN       NaN  ...        NaN        NaN        NaN
-575.830261       1.0       NaN       NaN  ...        NaN        NaN        NaN
...               ...       ...       ...  ...        ...        ...        ...
 163.963531       NaN       1.0       NaN  ...        NaN        NaN        NaN
 165.711227       NaN       1.0       NaN  ...        NaN        NaN        NaN
 166.193924       NaN       1.0       NaN  ...        NaN        NaN        NaN
 167.252563       NaN       1.0       NaN  ...        NaN        NaN        NaN
 171.529709       NaN       1.0       NaN  ...        NaN        NaN        NaN

[395644 rows x 40 columns]

In [ ]:
infile2 = open('/content/drive/My Drive/Y_train_float32.pickle', 'rb')

In [ ]:
y_train = pickle.load(infile2)
y_train.shape

(9933, 2)

In [ ]:
print(y_train)

[[4. 1.]
 [2. 0.]
 [4. 1.]
 ...
 [4. 1.]
 [4. 1.]
 [3. 2.]]


In [ ]:
feat_cols = ['feature'+str(i) for i in range(y_train.shape[1])]
y_train_pd = pd.DataFrame(y_train,columns=feat_cols)

In [ ]:
y_train_pd.head()

feature0  feature1
0       4.0       1.0
1       2.0       0.0
2       4.0       1.0
3       6.0       2.0
4       4.0       1.0

In [ ]:
y_train_pd.describe()

feature0     feature1
count  9933.000000  9933.000000
mean      3.556629     0.937481
std       1.630157     0.723726
min       0.000000     0.000000
25%       3.000000     0.000000
50%       4.000000     1.000000
75%       4.000000     1.000000
max       6.000000     2.000000

In [ ]:
y_train_pd.apply(pd.Series.value_counts)

feature0  feature1
0.0      1105    2931.0
1.0       267    4692.0
2.0       267    2310.0
3.0      1724       NaN
4.0      4692       NaN
5.0       681       NaN
6.0      1197       NaN

In [ ]:
infile3 = open('/content/sample_data/X_dev_audio_mfcc.pickle', 'rb')
x_dev = pickle.load(infile3)
x_dev.shape
x_dev.dtype
print(x_dev)

[[-252.0498       98.24591      -1.072963   ...   -1.1104983
    -4.0376935    -0.8147158 ]
 [-278.11868     120.15809     -19.028708   ...   -0.45414522
    -5.82676      -2.2900512 ]
 [-400.59976     159.424       -95.56356    ...   -1.5683845
    -3.415624     -4.8187585 ]
 ...
 [-294.0524      107.34596     -16.764824   ...   -1.4433427
    -4.3041177    -3.442549  ]
 [-353.11578     127.3339      -11.628155   ...   -3.314541
    -6.2671638    -3.3455515 ]
 [-352.1924      129.09164     -20.989237   ...   -3.8237555
    -6.3091154    -3.80219   ]]


In [ ]:
x_dev.shape

(1102, 40)

In [ ]:
infile4 = open('/content/sample_data/Y_dev_float32.pickle', 'rb')
y_dev = pickle.load(infile4)

In [ ]:
y_dev.shape

(1102, 2)

In [ ]:
print(y_dev)

[[5. 0.]
 [6. 0.]
 [4. 1.]
 ...
 [4. 1.]
 [4. 1.]
 [4. 1.]]


In [ ]:
a = y_dev[:,0]
y_dev.shape

(1102, 2)

In [ ]:
a.shape
print(np.unique(a))

[0. 1. 2. 3. 4. 5. 6.]


In [ ]:
b = y_dev[:,1]
b.shape

(1102,)

In [ ]:
print(np.unique(b))

[0. 1. 2.]


In [ ]:
x_train = x_train_dict.data
x_train

In [ ]:
import pandas as pd
feat_cols = ['feature'+str(i) for i in range(x_train_dict.shape[1])]
x_train_pd = pd.DataFrame(x_train_dict,columns=feat_cols)

In [ ]:
x_train_pd.tail()

feature0    feature1   feature2  ...  feature37  feature38  feature39
9928 -237.423492  130.749863 -58.501762  ...  -0.858047  -2.355972   6.037376
9929 -333.517395  145.444885 -69.295616  ...  -4.441897  -2.545352   0.720820
9930 -294.260071  112.519043 -40.892193  ...   0.084091  -0.791240   1.985936
9931 -346.273315  108.435432 -36.931839  ...  -0.831726  -0.909746   1.418372
9932 -338.791840  112.948410 -10.606875  ...  -1.547176  -5.774555  -2.567724

[5 rows x 40 columns]

In [ ]:
from sklearn.decomposition import PCA
pca = PCA(n_components=3)
pc = pca.fit_transform(x_train_dict)

In [ ]:
feat_col = ['Principal Component'+str(i) for i in range(pc.shape[1])]
pc_df = pd.DataFrame(pc, columns = feat_col)

In [ ]:
pc_df.tail()

Principal Component0  Principal Component1
9928            -79.275558            -41.079353
9929             14.701262            -65.749977
9930            -19.671225            -20.532780
9931             32.829487            -19.397982
9932             28.539810            -11.535717

In [ ]:
pca.explained_variance_ratio_

array([0.7639655 , 0.06972394], dtype=float32)

In [ ]:
pc_df.shape

(9933, 2)

In [ ]:
y_train.shape

NameError: ignored

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_train_dict, y_train, test_size = 0.2,random_state = 0)

ValueError: ignored

In [ ]:
x_train.shape
y_train.shape

(7946, 2)

In [ ]:
sc = StandardScaler()
sc_1 = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
y_train = sc_1.fit_transform(y_train)
y_test = sc_1.transform(y_test)

model = Sequential()
model.add(Dense(20, input_dim=40, kernel_initializer='normal', activation='relu'))
model.add(Dense(20, kernel_initializer='normal', activation='relu'))
model.add(Dense(20, kernel_initializer='normal', activation='softmax'))
model.add(Dense(6, kernel_initializer='normal'))
model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(x_train, y_train, batch_size = 32, epochs = 100, verbose = 2, validation_split = 0.2)
model.evaluate(x_test, y_test, batch_size = 32, verbose = 2)




Train on 6356 samples, validate on 1590 samples
Epoch 1/100
 - 2s - loss: 0.9911 - val_loss: 1.0184
Epoch 2/100
 - 1s - loss: 0.9731 - val_loss: 1.0162
Epoch 3/100
 - 1s - loss: 0.9625 - val_loss: 1.0268
Epoch 4/100
 - 1s - loss: 0.9570 - val_loss: 1.0200
Epoch 5/100
 - 1s - loss: 0.9483 - val_loss: 1.0249
Epoch 6/100
 - 1s - loss: 0.9426 - val_loss: 1.0236
Epoch 7/100
 - 1s - loss: 0.9363 - val_loss: 1.0219
Epoch 8/100
 - 1s - loss: 0.9299 - val_loss: 1.0244
Epoch 9/100
 - 1s - loss: 0.9250 - val_loss: 1.0241
Epoch 10/100
 - 1s - loss: 0.9198 - val_loss: 1.0432
Epoch 11/100
 - 1s - loss: 0.9172 - val_loss: 1.0272
Epoch 12/100
 - 1s - loss: 0.9093 - val_loss: 1.0356
Epoch 13/100
 - 1s - loss: 0.9042 - val_loss: 1.0401
Epoch 14/100
 - 1s - loss: 0.8977 - val_loss: 1.0394
Epoch 15/100
 - 1s - loss: 0.8940 - val_loss: 1.0484
Epoch 16/100
 - 1s - loss: 0.8904 - val_loss: 1.0498
Epoch 17/100
 - 1s - loss: 0.8831 - val_loss: 1.0886
Epoch 18/100
 - 1s - loss: 0.8786 - val_loss: 1.0604
Epoch 1

1.2495338979285449